[package]
name = "gnobbler"
version = "0.3.38"
edition = "2024"

[dependencies]
macroquad = { version = "0.4.14", features = ["audio"] }
image = "0.24.9"
asefile = "0.3.8"
num-derive = "0.4.2"
num-traits = "0.2.19"
impl-new-derive = "0.1.3"
include_dir = "0.7.4"
